name: Deploy Site

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
    
    - name: Checkout VCS
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    
    - name: Install Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    
    - name: Build Site
      run: hugo
    
    - name: Deploy
      run: hugo deploy --target=s3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}